USE [master]
GO

/****** Object:  Database [GT]    Script Date: 6/27/2023 3:13:52 AM ******/
CREATE DATABASE [GT]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'GT', FILENAME = N'C:\Program Files (x86)\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\GT.mdf' , SIZE = 3264KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'GT_log', FILENAME = N'C:\Program Files (x86)\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\GT_log.ldf' , SIZE = 816KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [GT] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [GT].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [GT] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [GT] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [GT] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [GT] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [GT] SET ARITHABORT OFF 
GO

ALTER DATABASE [GT] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [GT] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [GT] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [GT] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [GT] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [GT] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [GT] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [GT] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [GT] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [GT] SET  ENABLE_BROKER 
GO

ALTER DATABASE [GT] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [GT] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [GT] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [GT] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [GT] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [GT] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [GT] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [GT] SET RECOVERY FULL 
GO

ALTER DATABASE [GT] SET  MULTI_USER 
GO

ALTER DATABASE [GT] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [GT] SET DB_CHAINING OFF 
GO

ALTER DATABASE [GT] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [GT] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [GT] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [GT] SET  READ_WRITE 
GO

